### ISSUE TITLE
terribly slow

### ISSUE THREAD

**Issue by gitfy** [s3u/JSONPath#14] opened 2013-07-17 19:47 UTC
The latest version is terribly slow, could you please check it.
Thanks.

**Comment by codan84** [comment] 2015-06-26 11:00
I just downloaded npm package with this and a simple query like $.results[*].groups[*].items on a json object with about 50 items spread across 10-15 groups takes over 5min! Same job with for loops ~20-30ms . So the problem still exists...

**Comment by brettz9** [comment] 2015-12-13 09:51
It looks like the sandbox code had been added (now since modified a bit but not at all optimized) around the time this issue was created. Could someone submit a PR (against `master`) adding a `testing.performance.js` file?

**Comment by brettz9** [comment] 2015-12-13 10:02
The sandbox/eval code might need to be added optionally, particular if we can incorporate an update of PR #4 . Some `eval()` (or ECMAScript parser) will still need to be used, however, in order to support the arbitrary JavaScript allowed in filters (but again, it could be made optional).

**Comment by brettz9** [comment] 2015-12-13 10:02
In any case, it will still be good to have some tests in place.

**Comment by nuclearspike** [comment] 2016-05-01 19:09
Are there any plans to look at speed improvements? Because right now I have natively written super complex queries over my 5000+ JSON objects that takes < 100ms and this takes forever for the most basic lookups (get the 400th element in the array) takes several seconds... I can't imagine people are using this in production... It's impossibly bad. A query should just generate a predicate function that is run  against the list. Check out the code for https://linqjs.codeplex.com/ it takes string queries with predicates and selectors for JSON data but does it's job in a fraction of what this library takes.

**Comment by nuclearspike** [comment] 2016-05-01 19:38
Aha! Anyone who wants a jsonpath library written by people who don't think basic queries should take seconds to perform, check out https://www.npmjs.com/package/jsonpath it's **significantly** faster and at the level of performance that could actually be run in production.

This repo really should be shut down because you're wasting people's time having them think this will do what they want at a reasonable speed. Can you imagine writing an web app that uses this library when every query takes several seconds to execute?

**Comment by brettz9** [comment] 2016-05-01 19:52
I've added a note to the README that others may wish to use `jsonpath` as we do not currently have the time to resolve, bearing in mind that it does not have our proprietary extensions.

**Comment by zb3** [comment] 2016-10-03 12:56
After analysing performance using devtools, I've noticed that the slowest part of code (93%!, which was over 27 seconds in my case) is this fragment:
```javascript
    // We check the resulting values for parent selections. For parent
    // selections we discard the value object and continue the trace with the
    // current val object
    return ret.reduce(function (all, ea) {
        return all.concat(ea.isParentSelector ? self._trace(ea.expr, val, ea.path, parent, parentPropName, callback) : ea);
    }, []);
```

Not only does concat create a new array each time, but the return array is also needlessly copied.
Another slow part is (unsurprisingly) this:
```javascript
function addRet (elems) {ret = ret.concat(elems);}
```

Maybe I could find more fragments, but I do not have any test data that is big enough. Those parts are trivial to rewrite (then it takes 1 second instead of 30), but my code is too low quality to post it here :)

**Comment by brettz9** [comment] 2016-10-03 22:52
Can you prepare a test case that produces a performance problem?

IIRC, part of the rationale here may be that unless one wishes to act by reference, it is safer to clone (`concat` making a shallow copy) and it also avoids the user from having to make their own clone which will iterate the entire object a second time.

A simple way to avoid the block which checks `isParentSelector` might be to add a property to the JSONPath object indicating that a parent selector is present and simply return `ret` if not.

**Comment by zb3** [comment] 2016-10-04 09:01
Okay, I've made a `test.performance.js` file with my case (based on @codan84 answer), however, note that I am running it on a very slow CPU that may be 5x slower than yours, so you may need to increase these numbers to make it fail, here's the gist:
https://gist.github.com/zb3/d6ea67cc7403c2e51caf0fca8bf18337

However, I don't really understand why this clone is needed, since the `ret` reference is not passed anywhere, so no other part of code can make use of that. Also, if you want to simply return it in case `isParentSelector` isn't present (which means we won't clone it in that case), why not support all cases? Correct me if I'm wrong.

Anyway, for anyone interested, here's the code I am currently using, that acts like the old one:
```javascript
    // We check the resulting values for parent selections. For parent
    // selections we discard the value object and continue the trace with the
    // current val object
    for (var t = 0, tt; t < ret.length; t++) {
        if (ret[t].isParentSelector) {
            var tmp = self._trace(ret[t].expr, val, ret[t].path, parent, parentPropName, callback);
            if (Array.isArray(tmp)) {
                ret[t] = tmp[0];

                for (tt = 1; tt < tmp.length; tt++) {
                    t++;
                    ret.splice(t, 0, tmp[tt]);
                }
            } else {
                ret[t] = tmp;
            }
        }
    }
```

And also a simpler version for the `addRet` part:
```javascript
    function addRet (elems) {
        if (Array.isArray(elems)) {
            for (var t = 0; t < elems.length; t++) {
                ret.push(elems[t]);
            }
        } else {
            ret.push(elems);
        }
    }
```

**Comment by brettz9** [comment] 2016-10-04 21:07
Wow, the `concat` change in `addRet` made a real difference too. Thanks @zb3 ! I added a couple minor optimizations on top of your code and also optimized one other `concat` situation that helped shave off some time.

It would be great if we could get some real-world testing to see how these new improvements in `master` are working and whether the concerns of this issue have been adequately addressed.

Other tested optimizations most welcome.

**Comment by feeloo007** [comment] 2016-10-06 09:22
Hi,

Performance problems seem related to the node's version.

I use meteor.js. Each meteor's version includes a different version of node.

meteor 1.3.1 == node v0.10.43
meteor 1.3.5.1 == node v0.10.46
meteor 1.4.1.1_1 node == v4.5.0

Performance are differents depending on node's version.

I use this code : https://gist.github.com/feeloo007/10d3f1fcf1e6152b0afd6d0716c04400

with node modules from bretz's master branch.

* v0.10.43
```
time /home/pg/.meteor/packages/meteor-tool/.1.3.1.hovf3o++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node main.js
[ '$ [\ Def \'] [0] [\ cells \ '] [0]', '$ [\ def \'] [0] [\ cells \ '] [1]']

real 0m0.147s
user 0m0.129s
sys 0m0.016s
```

* v0.10.46
```
time /home/pg/.meteor/packages/meteor-tool/.1.3.5_1.1ek9hpx++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node main.js
[ '$ [\ Def \'] [0] [\ cells \ '] [0]', '$ [\ def \'] [0] [\ cells \ '] [1]']

real 0m2.556s
user 0m2.463s
sys 0m0.068s
```

* v4.5.0
```
time /home/pg/.meteor/packages/meteor-tool/.1.4.1_1.1f05xpi++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node main.js
[ '$ [\ Def \'] [0] [\ cells \ '] [0]', '$ [\ def \'] [0] [\ cells \ '] [1]']

real 0m0.095s
user 0m0.083s
sys 0m0.011s
```

node 0.10.46 has really poor performance (x20 factor).

If I use npmjs' version of jsonpath-plus, performance are similar.

* v0.10.43
```
time /home/pg/.meteor/packages/meteor-tool/.1.3.1.hovf3o++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node main.js
[ '$[\'def\'][0][\'cells\'][0]', '$[\'def\'][0][\'cells\'][1]' ]

real    0m0.173s
user    0m0.138s
sys     0m0.016s
```

* v0.10.46
```
time /home/pg/.meteor/packages/meteor-tool/.1.3.5_1.1ek9hpx++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node main.js
[ '$[\'def\'][0][\'cells\'][0]', '$[\'def\'][0][\'cells\'][1]' ]

real    0m2.541s
user    0m2.458s
sys     0m0.049s
```

* v4.5.0
```
time /home/pg/.meteor/packages/meteor-tool/.1.4.1_1.1f05xpi++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node main.js
[ '$[\'def\'][0][\'cells\'][0]', '$[\'def\'][0][\'cells\'][1]' ]

real    0m0.100s
user    0m0.086s
sys     0m0.012s
```

I hope this information may be useful. I don't know if issue is specific to meteor's node version.

bests regards

Philippe

**Comment by zb3** [comment] 2016-10-06 11:04
@feeloo007 , I've checked this in browsers and in node v6.7.0, but wasn't able to reproduce...
Maybe if you could run this with the `--prof` node option and share the resulting log file, it could help locating the problem (which may as well be in node, not JSONPath)

**Comment by feeloo007** [comment] 2016-10-10 14:18
Hi @zb3,

I'm not comfortable with this tool (--prof).

But clearly, the file is much bigger with this release 0.10.46.

[https://gist.github.com/feeloo007/f61d0b4bd37015a257e2cd80392784b7]

I think is a node problem, not JSONPath.

Thanks for your feedback.

Best regards

**Comment by amitguptagwl** [comment] 2017-01-23 07:01
I tested the same test against jsonpath and the result is; (node 5.2.0)

```json
{
    "testname": "jsonpathplus: Big data: $.results[*].groups[*].items[42]",
    "tps": 12.396779508231717
},
{
    "testname": "jsonpath: Big data: $.results[*].groups[*].items[42]",
    "tps": 0.9402719728192066
}
```

Same test on node 7 on [travisci](https://travis-ci.org/NaturalIntelligence/comparejs/builds/194379946)
```json
{
    "testname": "jsonpathplus: Big data: $.results[*].groups[*].items[42]",
    "tps": 10.039359771795878
},
{
    "testname": "jsonpath: Big data: $.results[*].groups[*].items[42]",
    "tps": 0.5350702778032731
}
```

**Comment by karanbhomiagit** [comment] 2017-06-07 07:03
@brettz9 

Hey guys, is there any ETA on when these issues would be fixed.
We are actively using JSONPath in our development, and would like to migrate to "jsonpath-plus".
If these issues are being resolved in near future, I can wait.
But if there is no foreseeable resolution to this in near future, we can start using "jsonpath" completely.

**Comment by brettz9** [comment] 2017-06-07 07:15
No ETA, though I'd recommend testing for yourself to see whether there are actual performance problems. Someone with time ought to be able to do some debugging with a profiler like in Chrome and see where any problem lies.

**Comment by andykais** [comment] 2019-05-16 05:02
I wanted to share with everyone the small perf testing I did comparing `jsonpath-plus`, `jsonpath`, and a number of other json querying libraries.
https://github.com/andykais/json-querying-performance-testing

My findings show that while `jsonpath-plus` is not the fastest in _all_ cases, it is still the most consistently fast, especially with larger cases. 
Feel free to pr some more perf cases if you wish so we can all see how they compare. 

Also, I did not discover any of the cases mentioned above where this library takes ~2 seconds on smallish objects, but again, feel free to add cases if you know of any.

**Comment by brettz9** [comment] 2019-05-16 06:34
That looks excellent!

I have updated the README to act on this information and will close this issue, leaving it to anyone to find (and hopefully add) any test cases which suggest any lingering performance issues.

But this is great news. I also took the chance to update the README to showcase jsonpath-plus' special features.

**Closed by brettz9** 2019-05-16 06:34 UTC
Labels: Optimization

**Comment by andykais** [comment] 2019-05-16 17:35
@brettz9 I put together a small pr to change the wording/fix a broken link in the readme. I appreciate my perf tests being called in the readme, but I wanted to clearly encourage others to run the benchmarks and add cases they felt were relevant. I dont feel comfortable being the only authority on this library's performance.

**Comment by brettz9** [comment] 2019-05-16 22:17
Understood, and I liked your solution...Thanks for all your work on this!

**Comment by brettz9** [comment] 2019-06-16 05:59
@andykais : If you hadn't noticed it, in issue #79 , @amitguptagwl referred to his own performance tests (at https://naturalintelligence.github.io/comparejs/?q=jsonpath-comparison ). Just mentioning in case it might raise any ideas for you as far as types of queries.
